# Generated by Django 4.0.4 on 2022-05-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_historicalvacancy_historicalfinder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvacancy',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='Скрыт?'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='hidden',
            field=models.BooleanField(default=True, verbose_name='Скрыт?'),
        ),
    ]
